<a href="https://colab.research.google.com/github/LiboMa/MachineLearning_Python/blob/master/neural_networks_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Networks from Scratch with Python Code and Math in Detail

https://towardsai.net/neural-networks-with-python

In [12]:
# Import required libraries:
import numpy as np
# Define input features:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print ("input features shape: ", input_features.shape)
print ("input features: \n",input_features)

# Define target output:
target_output = np.array([[0,1,1,1]])

# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)
print("target output shape: ", target_output.shape)
print ("target output: \n",target_output)

# Define weights:
weights = np.array([[0.1],[0.2]])
print("initial weights' shape: ", weights.shape)
print ("initial weights: \n",weights)

# initial Bias:
bias = 0.3
# Learning Rate:
lr = 0.05


input features shape:  (4, 2)
input features: 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
target output shape:  (4, 1)
target output: 
 [[0]
 [1]
 [1]
 [1]]
initial weights' shape:  (2, 1)
initial weights: 
 [[0.1]
 [0.2]]


In [39]:
# Sigmoid function(classical method):
def sigmoid(x):
 return 1/(1+np.exp(-x))

# Derivative of sigmoid function (for back propagation):
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:

# ReLU function(Morden method):
def ReLU(x):
  x = np.maximum(0, x)
  return x
# Derivative of ReLU function (for back propagation):
def RuLU_der(x):
  return ReLU(x) * (1 - ReLU(x))

History_or_loss = []
# Running our code 10000 times:
for epoch in range(10000):
 inputs = input_features
# Feedforward input:
 in_o = np.dot(inputs, weights) + bias
# Feedforward output:
 out_o = sigmoid(in_o)
#  out_o = ReLU(in_o)

 print("output of feedforward: ", out_o)

# Backpropogation 
# Calculating error
 error = out_o - target_output
 
 #Going with the formula:
 x = error.sum()
 print("loss of calculation: ",x)
 
 # Calculating derivative:
 derror_douto = error
 douto_dino = sigmoid_der(out_o)
#  douto_dino = RuLU_der(out_o)
 
 #Multiplying individual derivatives:
 deriv = derror_douto * douto_dino 
 
 #Multiplying with the 3rd individual derivative:
 #Finding the transpose of input_features:
 inputs = input_features.T
 deriv_final = np.dot(inputs,deriv)
 
 #Updating the weights values:
 weights -= lr * deriv_final 
 #Updating the bias weight value:
 for i in deriv:
  bias -= lr * i #Check the final values for weight and biasprint (weights)

print("weights after back-propagation ->", weights) 
print ("bias after backpropagation ->", bias)



Streaming output truncated to the last 5000 lines.
 [0.9999997 ]]
loss of calculation:  -0.00014433630985088465
output of feedforward:  [[0.01041965]
 [0.9947182 ]
 [0.99471811]
 [0.9999997 ]]
loss of calculation:  -0.00014433349647203358
output of feedforward:  [[0.01041938]
 [0.99471834]
 [0.99471825]
 [0.9999997 ]]
loss of calculation:  -0.00014433068319044673
output of feedforward:  [[0.01041911]
 [0.99471847]
 [0.99471839]
 [0.9999997 ]]
loss of calculation:  -0.00014432787000573724
output of feedforward:  [[0.01041884]
 [0.99471861]
 [0.99471852]
 [0.9999997 ]]
loss of calculation:  -0.00014432505691809247
output of feedforward:  [[0.01041857]
 [0.99471875]
 [0.99471866]
 [0.9999997 ]]
loss of calculation:  -0.0001443222439275818
output of feedforward:  [[0.0104183 ]
 [0.99471888]
 [0.9947188 ]
 [0.9999997 ]]
loss of calculation:  -0.00014431943103362238
output of feedforward:  [[0.01041803]
 [0.99471902]
 [0.99471893]
 [0.9999997 ]]
loss of calculation:  -0.00014431661823673114


In [40]:
# Making Prediction from new inputs
#Taking inputs:
single_point = np.array([1,0])
#1st step:
result1 = np.dot(single_point, weights) + bias 
#2nd step:
result2 = sigmoid(result1) 
#Print final result
print("1st prediction of [1,1], a or b",np.round(result2,4))


#Taking inputs:
single_point = np.array([1,1]) 
#1st step:
result1 = np.dot(single_point, weights) + bias 
#2nd step:
result2 = sigmoid(result1) 
#Print final result
print("2nd prediction of [1,1], a or b",np.round(result2,4))

#Taking inputs:
single_point = np.array([0,0]) 
#1st step:
result1 = np.dot(single_point, weights) + bias 
#2nd step:
result2 = sigmoid(result1) 
#Print final result
print("3rd prediction of [0,0], a or b",np.round(result2,4))


1st prediction of [1,1], a or b [0.9949]
2nd prediction of [1,1], a or b [1.]
3rd prediction of [0,0], a or b [0.0102]


In [ ]:
# Import required libraries:
import numpy as np# Define input features:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)# Define target output:
target_output = np.array([[0,1,1,1]])# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)# Define weights:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
print (weights)# Define learning rate:
lr = 0.05# Sigmoid function:
def sigmoid(x):
 return 1/(1+np.exp(-x))# Derivative of sigmoid function:
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:
# Running our code 10000 times:for epoch in range(10000):
 inputs = input_features#Feedforward input:
 pred_in = np.dot(inputs, weights)#Feedforward output:
 pred_out = sigmoid(pred_in)#Backpropogation 
 #Calculating error
 error = pred_out - target_output
 x = error.sum()
 
 #Going with the formula:
 print(x)
 
 #Calculating derivative:
 dcost_dpred = error
 dpred_dz = sigmoid_der(pred_out)
 
 #Multiplying individual derivatives:
 z_delta = dcost_dpred * dpred_dz#Multiplying with the 3rd individual derivative:
 inputs = input_features.T
 weights -= lr * np.dot(inputs, z_delta)
 
 
#Taking inputs:
single_point = np.array([1,0])#1st step:
result1 = np.dot(single_point, weights)#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([0,0])#1st step:
result1 = np.dot(single_point, weights)#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([1,1])#1st step:
result1 = np.dot(single_point, weights)#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)

(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 1)
[[0]
 [1]
 [1]
 [1]]
(2, 1)
[[0.1]
 [0.2]]
[0.52497919]
[0.5]
[0.57444252]


In [ ]:
# Import required libraries:
import numpy as np# Define input features:
input_features = np.array([[1,0,0,1],[1,0,0,0],[0,0,1,1],
 [0,1,0,0],[1,1,0,0],[0,0,1,1],
 [0,0,0,1],[0,0,1,0]])
print (input_features.shape)
print (input_features)# Define target output:
target_output = np.array([[1,1,0,0,1,1,0,0]])# Reshaping our target output into vector:
target_output = target_output.reshape(8,1)
print(target_output.shape)
print (target_output)# Define weights:
weights = np.array([[0.1],[0.2],[0.3],[0.4]])
print(weights.shape)
print (weights)# Bias weight:
bias = 0.3# Learning Rate:
lr = 0.05# Sigmoid function:
def sigmoid(x):
 return 1/(1+np.exp(-x))# Derivative of sigmoid function:
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:
# Running our code 10000 times:for epoch in range(10000):
 inputs = input_features#Feedforward input:
 pred_in = np.dot(inputs, weights) + bias#Feedforward output:
 pred_out = sigmoid(pred_in)#Backpropogation 
 #Calculating error
 error = pred_out - target_output
 
 #Going with the formula:
 x = error.sum()
 print(x)
 
 #Calculating derivative:
 dcost_dpred = error
 dpred_dz = sigmoid_der(pred_out)
 
 #Multiplying individual derivatives:
 z_delta = dcost_dpred * dpred_dz#Multiplying with the 3rd individual derivative:
 inputs = input_features.T
 weights -= lr * np.dot(inputs, z_delta)#Updating the bias weight value:
 for i in z_delta:
  bias -= lr * i#Printing final weights: 

print (weights)
print ("\n\n")
print (bias)#Taking inputs:
single_point = np.array([1,0,0,1])#1st step:
result1 = np.dot(single_point, weights) + bias#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([0,0,1,0])#1st step:
result1 = np.dot(single_point, weights) + bias#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([1,0,1,0])#1st step:
result1 = np.dot(single_point, weights) + bias#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)

(8, 4)
[[1 0 0 1]
 [1 0 0 0]
 [0 0 1 1]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 1 0]]
(8, 1)
[[1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]]
(4, 1)
[[0.1]
 [0.2]
 [0.3]
 [0.4]]
[[0.1]
 [0.2]
 [0.3]
 [0.4]]



0.3
[0.68997448]
[0.64565631]
[0.66818777]
